services:
  redis:
    container_name: redis
    image: redis:latest
    networks:
      - n_flask_redis_app
    ports:
      - "6379:6379"

  flask_redis_app:
    container_name: flask_redis_app
    image: flask-redis-app:latest
    stop_signal: SIGINT
    networks:
      - n_flask_redis_app
    ports:
      - "5000:5000"
    depends_on:
      - redis

networks:
  n_flask_redis_app:
    driver: bridge
