services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    networks:
      - flask_redis_app
    ports:
      - "6379:6379"

  flask_redis_app:
    container_name: flask-app
    build:
      target: final
    stop_signal: SIGINT
    networks:
      - flask_redis_app
    ports:
      - "5000:5000"
    depends_on:
      - redis

networks:
  flask_redis_app:
    driver: bridge
    name: flask-redis-app
